### PR TITLE
Add more AliExpress links

### PR DESCRIPTION
**Pull request by Eloren1**

### CODE REVIEW

**Comment by Eloren1** [comment]
Заменяемы ли 0603 резисторы на 806k?

**Comment by Eloren1** [comment]
Are the 0603 806k resistors replaceable?

**Comment by yumagulovrn** [comment]
@Eloren1 You can replace it with 820k resistor, but voltage sensing circuit (for battery status) will give somewhat invalid values

**Review by yumagulovrn — APPROVED** [review]

**Comment by yumagulovrn** [comment]
Tooks good! Thank you!

**Pull request merged**
